version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    ipc: host

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'
    ipc: host

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "snakeeyes.app:create_app()"
    env_file:
      - '.env'
    volumes:
      - '.:/snakeeyes'
    ports:
      - '8000:8000'
    ipc: host

  celery:
    build: .
    command: celery -A snakeeyes.blueprints.contact.tasks worker
    env_file:
      - '.env'
    volumes:
      - '.:/snakeeyes'
    ipc: host

volumes:
  postgres:
  redis:
