postgres:
  image: postgres:9.4.1
  environment:
    POSTGRES_USER: catwatch
    POSTGRES_PASSWORD: bestpassword
  ports:
    - 5432:5432
  volumes:
    - ~/.docker-volumes/catwatch/postgresql/data:/var/lib/postgresql/data

redis:
  image: redis:2.8.19
  ports:
    - 6379:6379
  volumes:
    - ~/.docker-volumes/catwatch/redis/data:/var/lib/redis/data